apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
    tier: frontend
  name: front
  namespace: todolist
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  type: NodePort
  selector:
    app: front
    tier: frontend
