#!/bin/bash

# 선택적 인수 처리
if [[ "$1" == "version" ]]
then
    echo "1.0.0"
    exit 0
fi

# 선택적 인수 처리
if [[ "$1" == "argocd" ]]
then
    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
elif [[ "$1" == "jenkins" ]]; then
    kubectl -n jenkins get secret jenkins -o jsonpath="{.data.jenkins-admin-password}" | base64 -d
elif [[ "$1" == "" ]]; then
    echo "서비스를 선택하세요 (argocd, jenkins)"
else
    echo "지원하지 않는 서비스입니다."
fi

exit 0;