kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-local
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi